name: automerge
on:
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' ||
      github.actor == 'dependabot' ||
      github.actor == 'dependabot-preview[bot]' ||
      github.actor == 'dependabot-preview' ||
      github.actor == 'github-actions[bot]' ||
      github.actor == 'firstmate-bot'
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.FIRST_MATE_PAT }}
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "merge"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "100000"
          MERGE_LABELS: ""
          BASE_BRANCHES: "main"